### PR TITLE
[#164829534] nsx-t support

### PR DESCRIPTION
**Pull request by xtreme-nitin-ravindran**
IPsec NSX-T compatibility

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @xtreme-nitin-ravindran

**Comment by xtreme-nitin-ravindran** [comment]
Sorry for the late reply. Can the changes be cherry-picked to 1.9 and 1.8 branches?

**Comment by RichardJJG** [comment]
@xtreme-nitin-ravindran, certainly; doing so now.

**Comment by jncd** [comment]
Hi @xtreme-nitin-ravindran 
I've pushed the update for v1.9 to production now too. 
https://docs.pivotal.io/addon-ipsec/1-9/index.html#limitations

**Pull request merged**
