### PR TITLE
Made clarifications

### PR DESCRIPTION
**Pull request by pivotal-david-osullivan**
Clarified use of optional flag when adding IPsec to existing PAS deployment.
Fixed command for verification of runtime-config in bosh2 (added '--name=ipsec').
Detailed files generated by downloadable openssl script.
Clarified 'renewing' section is for renewing already expired certs.

### CODE REVIEW

**Comment by ghanna2017** [comment]
Thanks @pivotal-david-osullivan

**Comment by jncd** [comment]
Hi @pivotal-david-osullivan 
Thanks for all these nice fixes and improvements!
After merging and editing, I cherry picked your changes to the live branches, v1.7 and v1.8. 
They sounded like things that apply to all versions, not something just for v1.9.
The note in best practices didn't render well at all, so I have deleted it. 
The instructions telling customers to do are in the procedures on page
What happens if customers don't set `optional` to `true`? Is it really just a "best practice" or is it something that customers really have to do to get IPsec working correctly?

**Comment by pivotal-david-osullivan** [comment]
@jncd Hi Jane, thank you for that! 
I had actually intended the note on the `optional` flag to appear _after_ 'Best Practices' and before the 'Step 1' section but I could not preview how it would render, apologies! 
It is a definite requirement that `optional` is set to `true` in the specific case that PAS has already been deployed. This allows IPsec to be installed without being 'enforced' so as not to break communication between existing components during initial installation.
Although it is mentioned as one of the last steps (13), it could be easily missed here so I was hoping to highlight this before any steps are completed given its importance. 
If you could render it a better way that would be great!

**Comment by jncd** [comment]
Hi @pivotal-david-osullivan 

Does this make sense?  

screen shot 2018-05-04 at 3 54 51 pm

I put it in the edge branch. Let me know if it needs adjustment. I'll copy to live doc versions on Monday.

**Comment by pivotal-david-osullivan** [comment]
That's perfect, thanks Jane! @jncd

**Pull request merged**
