### PR TITLE
[#142415667] adding documentation on UDP encapsulation

### PR DESCRIPTION
**Pull request by kcmannem**
Signed-off-by: Yoon Jean Kim <ykim@pivotal.io>

Please add to 1.8 branch as well.

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @kcmannem ! 
When you say "This property should be set to `false` otherwise." 
I'm a bit confused about the exact meaning of some of your words:

"should" = Can we just say "Set the property to `false` on ..."?

"otherwise" => What is the opposite of Linux-only? Is it "Windows"? Or "mixed Linux and Windows deployments"? 

TIA, Jane

**Comment by kcmannem** [comment]
The property should be false in mixed deployments, but true when used by linux only. I think the comment should be more specific, maybe along the lines of "This property should be set to `false` in mixed deployments."

**Comment by snneji** [comment]
Hi @kcmannem You add a warning in this PR that if you don't have a linux only deployment, set force_udp_encapsulation to false. Why is this a "warning" - what are the consequences of setting it to true for non-linux-only deployments?

Thanks, Samia and Gigi

**Comment by kcmannem** [comment]
@snneji if the warning is not followed (setting to true on mixed deployments), the deployment will break. Since communication between linux and windows will be blocked. This is because Windows does not support this property.

**Pull request merged**
