### PR TITLE
Update ipsec doc for rotating chain ca certs

### PR DESCRIPTION
**Pull request by JennyUWaterloo**
[#153501137]

Signed-off-by: Yoon Jean Kim <ykim@pivotal.io>

### CODE REVIEW

**Comment by ghanna2017** [comment]
Thanks @JennyUWaterloo

**Comment by jncd** [comment]
@JennyUWaterloo @snneji @ghanna2017 
Hi, I have a question about the note you added: 
> The root and the intermediate certificates cannot have the same subject/common name.
We're not supposed to use the slash, so in thinking about how to rewrite it, I realized I didn't know what this meant. I assume that there is just one name (which is called a "common name" by some people and "subject name" by other people).  
Can you point out where the subject (or common) name in the examples on this page? 
I searched the doc and didn't find another reference to this name. 
TIA, Jane

**Comment by johnpfield** [comment]
For the documentation we can adjust to **subjectName**.    (no whitespace, capitalized N). That is a named field in the certificate blob standards document (RFC 5280) that is a key=value pair, with a string value. 

One of the tokens in that string is typically the abbreviation CN, which stands for commonName.  For example, the key **subjectName** could have a value like _CN=John Field, OU=R&D, O=Pivotal Software, C=US_.

So, developers often loosely use "subject name" and "common name" interchangeably.

**Comment by jncd** [comment]
Thanks @johnpfield 
One more thing: I'm assuming that the contents of this PR also need to be added to the master branch, ready for the next (v1.9) release of the IPsec Add-on for PCF.  Be sure to let me know if this is not the case, and I'll revert those commits to master.

**Pull request merged**
