### PR TITLE
Include limitation around c2c traffic

### PR DESCRIPTION
**Pull request by kirederik**
> Which other branches should this be merged with (if any)?

1.9.

Thanks!

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @kirederik

**Comment by jncd** [comment]
Hi @kirederik 
Thanks for the PR. 
Does this refer to communication between apps that is permitted through "container to container networking" policies on TAS?
https://docs.pivotal.io/application-service/2-11/concepts/understand-cf-networking.html#app-comm 

Also, I just saw: https://docs.pivotal.io/application-service/2-11/concepts/understand-cf-networking.html#securing-traffic which explicitly says it can be done.  (We might need to edit that page too.)

_proposed text for IPsec limitations:_
> + "IPsec for VMware Tanzu cannot be configured to encrypt container to container traffic. For general information about securing this traffic, see [Securing Container-to-Container Traffic](https://docs.pivotal.io/application-service/2-11/concepts/understand-cf-networking.html#securing-traffic)."

I'll be around Monday afternoon, LMK if it's easier to zoom about this.

**Comment by kirederik** [comment]
@jncd Thanks for pointing out the TAS documentation. I'll double check with the team to figure out which one is correct and will circle back in this PR 🤔

**Comment by jncd** [comment]
Thanks @kirederik !
Let me know what you figure out. I'm at work now (7:30 am pdt). Do you think we could finish this PR story today?

**Comment by kirederik** [comment]
@jncd I hope to hear back today; I'll update this one accordingly!

**Comment by kirederik** [comment]
Clarified! 

The limitation here is that its not possible to exclude Diego Cells from IPSec and enable it for C2C communication only.

How does the one below sounds?

> IPsec for VMware Tanzu cannot be configured to encrypt container to container traffic while excluding VM to VM traffic in the Diego Cell. For general information about securing this traffic, see Securing Container-to-Container Traffic.

Or

> IPsec for VMware Tanzu cannot be configured to encrypt traffic in overlay networks while excluding the traffic in the underlay network. For general information about securing this traffic, see Securing Container-to-Container Traffic.

**Comment by jncd** [comment]
Hello @kirederik 
Thanks for investigating...
 
Hmm, so how do customers exclude VM to VM traffic in the Diego Cell? I don't see these terms or "underlay network" in the IPsec docs. 

I'm guessing it is something to do with [no_ipsec_subnets](https://docs.pivotal.io/addon-ipsec/1-9/installing.html#create-mfest) ? 

Can we make the connection, like: 
> If you specify the X subnet as a `no_ipsec_subnets` when you create the IPsec manifest, then IPsec for VMware Tanzu cannot be configured to encrypt container to container traffic.

**Comment by kirederik** [comment]
@jncd 

> I'm guessing it is something to do with no_ipsec_subnets ?
Yes


For a bit more of background:

This was raised out of the following customer question: "Can I configure IPSec to encrypt only container to container traffic?". What they tried in the IPSec manifest:

```
no_ipsec_subnets:
- 100.127.10.0/24       # This is the network where BOSH will assign IPs for the VMs. The underlying network
ipsec_subnets:
- 10.240.0.0/12.        # This is the overlay network, where C2C communication happens
```

The configuration above will not work. IPSec must include the physical (underlay) network to encrypt overlay network traffic; IPSec won't have visibility of the overlay network otherwise.

image

With that in mind, mabe the following is clearer?

> Container to Container traffic in overlay networks will not be encrypted when the underlying network is under `no_ipsec_subnets`. That means IPSec for VMware Tanzu cannot be configured to encrypt only C2C communications.

Maybe we can eve drop the second phrase and end in the first period 🤔

**Comment by jncd** [comment]
Hello @kirederik 

1. Thank you for the brilliant explanation. 

2. Could I / should I inquire about getting the above explanation into a Knowledge Base article? Seems like it's already written and could drop right into the KB format. Was there a support engineer involved in this customer issue? 

3. I think I lead us astray with `no_ipsec_subnet`. After typing in what you wrote, I reread [Create the IPsec Manifest](https://docs.pivotal.io/addon-ipsec/1-9/installing.html).  I think it's not enough to leave the underlying subnet off the no-list. I think it has to be _included_ in the yes-list.   (Does that make sense?)
Assuming that, I rewrote our blurb as follows:
> * Container-to-container traffic is not encrypted unless the underlying network is also encrypted.
  Both the overlay network for container-to-container networking and the underlying, physical network
  for Diego Cell to Diego Cell networking must be included in the `ipsec_subnets` section of the IPsec manifest.

I look forward to your thoughts.

**Comment by kirederik** [comment]
> Could I / should I inquire about getting the above explanation into a Knowledge Base article? Seems like it's already written and could drop right into the KB format. Was there a support engineer involved in this customer issue?

Dipal Patel raised the question on Slack. Maybe we should create a kb 😄 

I think the rewrite is spot on 👍🏽

Lets ship it!

**Comment by jncd** [comment]
It's live: https://docs.pivotal.io/addon-ipsec/1-9/#limitations

I'll inquire about KB articles tomorrow.

**Pull request merged**
