### PR TITLE
Update renewing.html.md.erb

### PR DESCRIPTION
**Pull request by johnpfield**
Added text to provide some additional background information on this procedure.

### CODE REVIEW

**Comment by jncd** [comment]
@johnpfield Merging this for now. So, you should be able to see it on the staging site soon: 
https://docs-pcf-staging.cfapps.io/addon-ipsec/1-8/renewing.html (pivotalcf/wilderror16)
Let me know about the 509 link and confirm versions.
Thanks!

**Comment by johnpfield** [comment]
@jncd Thanks, the "above" reference was just to generally say that the installation procedure requires the operator to supply certificates in the deployment manifest yml.  That is described in step 2 of [this page](https://docs.pivotal.io/addon-ipsec/installing.html#linux).  Feel free to rework that phrasing for better clarity.

**Comment by johnpfield** [comment]
With respect to versions, yes this applies to all versions.

**Comment by johnpfield** [comment]
Are there additional steps needed before this change moves from staging to production?

**Comment by jncd** [comment]
Should be in production now. Thanks for the reminder @johnpfield 
Just one more question: what are the symptoms that customers experience when their certificates are expired? 
Can we add the symptom to this section: https://docs.pivotal.io/addon-ipsec/1-8/troubleshooting.html#ipsec-runtime-issues ? 
And point to "Renewing Expired IPsec Certificates" for the solution.

**Comment by johnpfield** [comment]
Expired certs will ruin your whole day.  Symptoms would look a lot like a complete system outage, with no prior warning.  However, a BOSH operator can follow the provided procedure to recover.

**Pull request merged**
